version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21

  build:
    commands:
      - echo "Building Spring Boot app"
      - cd demo
      - mvn clean package -DskipTests

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - demo/target/demo-0.0.1-SNAPSHOT.jar