version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
      nodejs: 20

  build:
    commands:
      - echo Building React Frontend
      - cd frontend
      - npm install
      - npm run build

      - echo Building Spring Boot Backend
      - cd ../demo
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests

artifacts:
  files:
    - '**/*'